### ISSUE TITLE
  java.lang.NoSuchFieldError: No field q of type I in class Lcom/bandyer/sdk_design/R$style

### ISSUE THREAD

**Issue by ThunderThrash** [Bandyer/Bandyer-Android-SDK#1]
Hello! I downloaded the code and compiled. So when i try to start a chat i obtain this error:

```
Process: com.bandyer.demo_android_sdk, PID: 18567
    java.lang.NoSuchFieldError: No field q of type I in class Lcom/bandyer/sdk_design/R$style; or its superclasses (declaration of 'com.bandyer.sdk_design.R$style' appears in /data/app/com.bandyer.demo_android_sdk-1/split_lib_slice_0_apk.apk)
        at com.bandyer.android_sdk.chat.BandyerChatActivity.onCreate(BandyerChatActivity.kt:104)
```

this happens when i call

`        startActivityForResult(chatIntent, START_CHAT_CODE);`

I try with Samsung galaxy S7 (android marshmallow) and Nexus 5x (android Oreo)

Thank you very much I'm waiting

**Comment by kristiyanP** [comment]
Thank you for letting us know!

We just found out that  bintray has messed up the release ```com.bandyer:bandyer-android-sdk:1.0.1```...

**Please update** to ```com.bandyer:bandyer-android-sdk:1.0.2```.

Feel free to re-open this issue if not resolved.

**Comment by ThunderThrash** [comment]
Now it works. thank you!
