### ISSUE TITLE
I need to know 2 user case about this SDK

### ISSUE THREAD

**Issue by ThunderThrash** [Bandyer/Bandyer-Android-SDK#2]
hello,

I need 2 information. I do not know if it's right to open an issue for this, but I do not know how to contact you otherwise.

1) I suppose it is not possible to open a chat with more than two users. Will there be a possibility in a future version?

2) Is it possible for a user instead of answering a call, joining an existing room with other users who are already conversing with each other?

If so how? By BandyerSDKClient.joinUrl? I tried but I did not succeed in this. Or maybe I did something wrong, it's not clear to me how.

**Comment by kristiyanP** [comment]
Just to be sure we checked joinUrl and it appears we did have a bug in there...

We released **v1.0.3** which fixes the bug with joinUrl and we also updated the demo app with state checks to avoid crashes.

Please update to v1.0.3 and check if your code already does these checks before joining:
https://github.com/Bandyer/Bandyer-Android-SDK/commit/f7fc49ab7ba364c2259eded9738312d83e9f7842
