### ISSUE TITLE
Video call not connecting

### ISSUE THREAD

**Issue by swap3848** [Bandyer/Bandyer-Android-SDK#6]
I am using your SDK for Android and i implemented your SDK properly but once i try to connect video call it's showing error "access denied finding property vendor.camera.aux.packagelist android".
  I checked with your demo app also i am facing same issue with your demo app.
And in log i got "Parcel: Reading a NULL string not supported here" this issue also.
Could you please help me to resolve this issue?

**Comment by kristiyanP** [comment]
Looks like a hardware issue.

Just a reminder, this SDK is a B2B solution that comes with a pricing.
You may contact us on our official channels (thread mail of your company) for a more in depth follow-up on your issue.
