### ISSUE TITLE
kaleyra_iconStyle is not working 

### ISSUE THREAD

**Issue by sivavigo** [Bandyer/Bandyer-Android-SDK#7]
I tried updating the kaleyra_iconStyle with custom icon, but it is not reflecting while call is in ongoing state.
Showing default Kaleyra logo

Code:
-------
`<style name="KaleyraCollaborationSuiteUI.CallWatermark" parent="KaleyraCollaborationSuiteUI.DefaultCallWatermark">
        <item name="kaleyra_iconStyle">@style/CallWatermark</item>
        <item name="kaleyra_titleStyle">@style/TitleWatermark</item>
    </style>

    <style name="CallWatermark" parent="KaleyraCollaborationSuiteUI.CallWatermarkImageView">
        <item name="android:src">@drawable/ic_launcher_vigo_life_round</item>
    </style>

    <style name="TitleWatermark" parent="KaleyraCollaborationSuiteUI.TextView.CallWatermark">
        <item name="android:text">Vigo life</item>
    </style>`

Screenshot
------------
<img width="341" alt="Screenshot 2023-07-04 at 10 36 30 AM" src="https://github.com/Bandyer/Bandyer-Android-SDK/assets/113036092/6c838331-8799-4e5f-9c11-fd568d7cf5eb">

**Comment by fede87** [comment]
Hi @sivavigo, could you please confirm that you are using our sample app logged with a custom QR code?
In this case the sample app will override the style and will use the logo that is embedded in the configuration QR code.
To effectively use a custom theme please use it in your app integration.
